using System.ComponentModel.DataAnnotations;

namespace ARAKDataSetup.Domains.ServerAccessDto;

/// <summary>
/// ORG_ID	ORG_UID	ORG_NAME	ORG_ALIAS	ORG_SLOGAN1	ORG_SLOGAN2	ORG_ADDR1	ORG_ADDR2	ORG_ADDR3	ORG_ADDR4	ORG_TEL1	ORG_TEL2	ORG_TEL3	ORG_FAX	ORG_EMAIL1	ORG_EMAIL2	ORG_EMAIL3	ORG_WEBSITE	ORG_IMG	WELCOME_DIALOG1	WELCOME_DIALOG2	DEFAULT_FONT_FACE	DEFAULT_FONT_SIZE	REP_SERVER	REP_FORMAT	REP_FOOTER1	REP_FOOTER2	EMP_IMG_TYPE	EMP_IMG_MAX_SIZE	OTHER_MAX_FILE_SIZE	DT_FMT	TIME_FMT	LOCAL_CURRENCY_NAME	LOCAL_CURRENCY_SYMBOL	CURRENCY_FMT	RESOURCE_IMAGE_PATH	SCANNED_IMAGE_PATH	DOCUMENT_PATH	BACKUP_PATH	OTHER_FILE_PATH	EMP_IMG_PATH	LAB_DATA_PATH	USER_DISPLAY_FMT	VENDOR_H1	VENDOR_H2	VENDOR_LOGO_PATH	PARTNER1_H1	PARTNER1_H2	PARTNER1_LOGO_PATH	PARTNER2_H1	PARTNER2_H2	PARTNER2_LOGO_PATH	RIS_IP	RIS_PORT	RIS_USER	RIS_PASS	RIS_URL	PACS_IP	PACS_PORT	PACS_URL1	PACS_URL2	PACS_URL3	PACS_DOMAIN	HIS_IP	HIS_PORT	HIS_DB_NAME	HIS_USER_NAME	HIS_USER_PASS	HIS_FIN_FLAG	WS_IP	WS_IP_PICTURE	WS_VERSION	ORM_SYNC_IP	ORM_SYNC_PORT	ORU_SYNC_IP	ORU_SYNC_PORT	HIS_SYNC_IP	HIS_SYNC_PORT	EDIT_ORDER_UNTIL	SCHEDULE_CONFIRM_TIME	SCHEDULE_APPROVAL_TIME	ALLOW_PARTIAL_PAYMENT	MIN_PARTIAL_PAYMENT	ADD_PENDING_INVOICE	INVOICE_KNOCK_OFF_POLICY	RETURN_ALLOWED_DAYS	RETURN_WHAT	OVER_DEPOSIT	SHOW_DF	IMG_FILE_PATH	CREATED_BY	CREATED_ON	LAST_MODIFIED_BY	LAST_MODIFIED_ON	GROUP_ID	IS_MAIN	VAT_PERCENTAGE	VERSION_NO	RELEASE_NOTE	PUBLISHED_ON	ORG_TIN	SKIP_QUEUE	IS_PHYSICAL_CHECKUP_VISIBLE	IS_CONSULTATION_NO_VISIBLE	IS_SKIP_CLINIC_TYPE_POPUP	DEFAULT_ENCOUNTER_TYPE_ID	DEFAULT_CASHCOUNTER_ID	DEFAULT_PHARMACY_LOCATION	IS_LIS_SHORT_FORM	IS_SAMPLE_WISE_COLLECT	RIS_COMPLETE_IN	PARENTORG_ID	LANG
/// </summary>
public class GBLEnvDto
{
    [Key]
    public int ORG_ID { get; set; }
    public string ORG_UID { get; set; }
    public string ORG_NAME { get; set; }
    public string ORG_ALIAS { get; set; }
    public string ORG_DESCRIPTION { get; set; }
}