using System.ComponentModel.DataAnnotations;

namespace ARAKDataSetup.Domains.ServerAccessDto;

/// <summary>
/// USER_ID	USER_UID
/// USER_NAME
/// SECURITY_QUESTION
/// SECURITY_ANSWER
/// PWD
/// UNIT_ID
/// JOBTITLE_ID
/// JOB_TYPE
/// TITLE_NLS
/// FNAME_NLS
/// MNAME_NLS	LNAME_NLS
/// TITLE_ENG	FNAME_ENG	MNAME_ENG	LNAME_ENG	ALIAS_NAME	GENDER	EMAIL_PERSONAL	EMAIL_OFFICIAL	PHONE_HOME	PHONE_MOBILE	PHONE_OFFICE	PREFERRED_PHONE	PABX_EXT	FAX_NO	DOB	BLOOD_GROUP	ADDRESS	DISTRICT_ID	PROVINCE_ID	ZIP_CODE	DEFAULT_LANG	RELIGION	AUTH_LEVEL_ID	REPORTING_TO
/// LAST_PWD_MODIFIED	CARD_NO	PLACE_OF_BIRTH	NATIONALITY	M_STATUS	IS_ACTIVE
/// SUPPORT_USER	CAN_KILL_SESSION	ALLOW_OTHERS_TO_FINALIZE	CAN_EXCEED_SCHEDULE	IMG_FILE_NAME
/// EMP_REPORT_FOOTER1	EMP_REPORT_FOOTER2	THEMES	MENU_LAYOUT	PROFILE_LAYOUT	IS_COMPACT	IS_GUEST
/// ORG_ID	CREATED_BY	CREATED_ON	LAST_MODIFIED_BY
/// LAST_MODIFIED_ON	PWD_HASH	PWD_SALT	TIMEZONE_ID	EMAIL_ACTIVATION_CODE
/// EMAIL_VERIFICATION_EXP_DATETIME	IS_EMAIL_VERIFIED	PW_RESET_EXP_DATETIME
/// PW_RESET_DATETIME	RESET_PW_CODE	HOST	PORT	SCHEME	IS_AUTO_REFRESH	REFRESH_TIME
/// COUNTRY_ID	DEFAULT_PAGE	CASH_COUNTER_ID	PHARMACY_LOCATION_ID	IS_PO_SIGNATORY	ALERT_ON_NEW_MESSAGE
/// </summary>
public class UserDto
{
    [Key]
    public int USER_ID { get; set; }
    public string USER_UID { get; set; }
    public string USER_NAME { get; set; }
    public string SECURITY_QUESTION { get; set; }
    public string SECURITY_ANSWER { get; set; }
    public string PWD { get; set; }
    public byte[] PWD_HASH { get; set; }
    public byte[] PWD_SALT { get; set; }
    public int UNIT_ID { get; set; }
    public int JOBTITLE_ID { get; set; }
    public string JOB_TYPE { get; set; }
    public bool IS_ACTIVE { get; set; } = true;
    public int ORG_ID { get; set; }

}